### ISSUE TITLE
Proposal: Make this collection more ansible-friendly? 

### ISSUE THREAD

**Issue by Warkdev** [IBM-Security/isam-ansible-collection#159]
Hello,

I've been reviewing lately what ansible offers as plug-in extensions and while I'm comparing that towards what this collection is using, I thought we could make this collection much friendly to ansible usage and way of working.

So far, I've in mind to:
- get an isva httpapi plug-in (rather than a connection plug-in which is lower level)
- try to leverage the network module resource design (which seems pretty adapted to configuration of devices likes isva) or, I discovered it lately, the network security resource module which seems to be designed to integrate natively the httpapi plug-in.
- maybe a cliconf or something closer (didn't look it yet) to handle the ssh connectivity if required (but I think the rest api to execute commands is working weel for most use cases)

Advantages of this approach:
- isva would be considered as a first class citizen of ansible, leveraging default variables from the inventory (yet very similar to what exists today with the connection plug-in)
- isva could be part of the facts gathering process, another benefit from being a good citizen
- units and integration tests as part of the CD pipeline, ensuring the quality of the overall collection
- no more ibmsecurity dependency which is a nice library but its integration into ansible is a bit too much hacky imho.

Some features I'd like to see:
- support of diff out of the box to see what changes were made
- support of check mode
- real modules to manage acl, objectspace, pop.. Instead of leaving that to the user

More ideas are welcome,

Cédric S.

**Comment by ram-ibm** [comment]
The intention of the framework was to be ansible "native". The framework supports check mode execution, idempotency, comparison of settings. There has been an effort to cover the pdadmin commands - there is a thread somewhere discussing it. Ansible facts are set as part of the initial connection - and it is leveraged extensively (see versioning logic),

It is possible that the same results could have been achieved differently...

**Comment by Warkdev** [comment]
Ans I think it made its purpose for several years now. Yet, with collections, you can now deliver a seamless experience to the user only through the collection, no need for an external module using eval of python functions, you can make module for each isva resource and use them like you would use any other modules.

I'm not criticizing the current delivered work, just willing to contribute into its modernization.

Regards.

**Comment by ram-ibm** [comment]
We actually worked with the RedHat team to create the Collection framework. They understood that we solved being ansible "native" differently - but the key is we are already a first class citizen!

**Comment by Warkdev** [comment]
Thank you Ram for your feedback,

I've indeed seen that there was a connection plugin on top of the collection which makes it more native and first class citizen compared to the isam-ansible-roles version. Sorry for that.

I'll state my ideas otherwise, which version do you prefer of the following code as an Ansible user ?

This one (add a loop around junction if you've 100 to create/check) and I'm probably forgetting some actions:

```yml
# The facts from this task will be used to determine if the next task can be run
- name: Get the activations on the appliance
  ibm.isam.isam:
    log: "{{ log_level | default('INFO') }}"
    force: "{{ force | default(False) }}"
    action: ibmsecurity.isam.base.activation.get
  register: ret_obj

# Configuring reverse proxy does not require a commit. So flush handlers now
# to ensure not to loose any prior pending changes.
- meta: flush_handlers

- name: Configure Reverse Proxy
  ibm.isam.isam:
    log: "{{ log_level | default('INFO') }}"
    force: "{{ force | default(False) }}"
    action: ibmsecurity.isam.web.reverse_proxy.instance.add
    isamapi:
      inst_name: "{{ create_reverseproxy_inst_name }}"
      admin_pwd: "{{ create_reverseproxy_admin_pwd }}"
      host: "{{ create_reverseproxy_host }}"
      listening_port: "{{ create_reverseproxy_listening_port }}"
      domain: "{{ create_reverseproxy_domain }}"
      admin_id: "{{ create_reverseproxy_admin_id }}"
      ssl_yn: "{{ create_reverseproxy_ssl_yn }}"
      key_file: "{{ create_reverseproxy_key_file }}"
      cert_label: "{{ create_reverseproxy_cert_label }}"
      ssl_port: "{{ create_reverseproxy_ssl_port }}"
      http_yn: "{{ create_reverseproxy_http_yn }}"
      http_port: "{{ create_reverseproxy_http_port }}"
      https_yn: "{{ create_reverseproxy_https_yn }}"
      https_port: "{{ create_reverseproxy_https_port }}"
      nw_interface_yn: "{{ create_reverseproxy_nw_interface_yn }}"
      ip_address: "{{ create_reverseproxy_ip_address }}"
  when: ('wga' in ret_obj['ansible_facts']['activations'])

# Set existing stanza(s)/entries in reverse proxy config file
- name: Set values into Reverse Proxy Configuration File
  ibm.isam.isam:
    log: "{{ log_level | default('INFO') }}"
    force: "{{ force | default(False) }}"
    action: ibmsecurity.isam.web.reverse_proxy.configuration.entry.set
    isamapi:
      reverseproxy_id: "{{ set_reverseproxy_conf_reverseproxy_id }}"
      stanza_id: "{{ item.stanza_id }}"
      entries: "{{ item.entries }}"
  with_items: "{{ set_reverseproxy_conf_entries }}"
  when: set_reverseproxy_conf_entries is defined and set_reverseproxy_conf_reverseproxy_id is defined
  notify:
  - Commit Changes
  - Restart Reverse Proxy

- name: Update a Junction - {{ set_junction_junction_point }}
  ibm.isam.isam:
    log: "{{ log_level | default('INFO') }}"
    force: "{{ force | default(False) }}"
    action: ibmsecurity.isam.web.reverse_proxy.junctions.set
    isamapi:
      junction_point: "{{ set_junction_junction_point }}"
      junction_type: "{{ set_junction_junction_type }}"
      reverseproxy_id: "{{ set_junction_reverseproxy_id }}"
      server_hostname: "{{ set_junction_server_hostname }}"
      server_port: "{{ set_junction_server_port }}"
      basic_auth_mode: "{{ set_junction_basic_auth_mode }}"
      stateful_junction: "{{ set_junction_stateful_junction }}"
      client_ip_http: "{{ set_junction_client_ip_http }}"
      scripting_support: "{{ set_junction_scripting_support }}"
      junction_cookie_javascript_block: "{{ set_junction_junction_cookie_javascript_block }}"
      virtual_hostname: "{{ set_junction_virtual_hostname }}"
      server_dn: "{{ set_junction_server_dn }}"
      query_contents: "{{ set_junction_query_contents }}"
      case_sensitive_url: "{{ set_junction_case_sensitive_url }}"
      windows_style_url: "{{ set_junction_windows_style_url }}"
      https_port: "{{ set_junction_https_port }}"
      http_port: "{{ set_junction_http_port }}"
      proxy_hostname: "{{ set_junction_proxy_hostname }}"
      proxy_port: "{{ set_junction_proxy_port }}"
      sms_environment: "{{ set_junction_sms_environment }}"
      vhost_label: "{{ set_junction_vhost_label }}"
      junction_hard_limit: "{{ set_junction_junction_hard_limit }}"
      junction_soft_limit: "{{ set_junction_junction_soft_limit }}"
      tfim_sso: "{{ set_junction_tfim_sso }}"
      remote_http_header: "{{ set_junction_remote_http_header }}"
      preserve_cookie: "{{ set_junction_preserve_cookie }}"
      cookie_include_path: "{{ set_junction_cookie_include_path }}"
      transparent_path_junction: "{{ set_junction_transparent_path_junction }}"
      mutual_auth: "{{ set_junction_mutual_auth }}"
      insert_session_cookies: "{{ set_junction_insert_session_cookies }}"
      request_encoding: "{{ set_junction_request_encoding }}"
      enable_basic_auth: "{{ set_junction_enable_basic_auth }}"
      key_label: "{{ set_junction_key_label }}"
      gso_resource_group: "{{ set_junction_gso_resource_group }}"
      version_two_cookies: "{{ set_junction_version_two_cookies }}"
      ltpa_keyfile: "{{ set_junction_ltpa_keyfile }}"
      authz_rules: "{{ set_junction_authz_rules }}"
      fsso_config_file: "{{ set_junction_fsso_config_file }}"
      server_uuid: "{{ set_junction_server_uuid }}"
      local_ip: "{{ set_junction_local_ip }}"
      delegation_support: "{{ set_junction_delegation_support }}"
      insert_ltpa_cookies: "{{ set_junction_insert_ltpa_cookies }}"
      http2_junction: "{{ set_junction_http2_junction }}"
      http2_proxy: "{{ set_junction_http2_proxy }}"
      sni_name: "{{ set_junction_sni_name }}"
  when:
    - set_junction_junction_point is defined
    - set_junction_junction_type is defined
    - set_junction_reverseproxy_id is defined
    - set_junction_server_hostname is defined
    - set_junction_server_port is defined
```

or this one ?

```yml
- name: Configuring reverse-proxy
  ibm.isam.isam_reverse_proxy:
    keystore: "{{ keystore_properties }}"
    config: "{{ reverse_proxy_configuration }}"
    jmt: "<path to JMT file or var>"
    dynurl: "<path to dynurl file>"
    fsso: "<list of fsso files>"
    junctions: "{{ list of junctions }}"
    objectspace: "{{ objectspace definition }}"
   policies: "{{ etc.. }}"
...
```

Seeing some of the bigger components as a resource may help to enhance drastically some user expectations and management of dependencies. Example, if I want to get rid of a STS Template, I first need to remove all STS Module Chains using it. Why can't a resource module taking care of STS chains do that for the user ?

With Network Resource Module state, you can also submit partial updates to a resource and be more user-friendly for ponctual operations.

Again, I'm not criticizing the current work which I think helped a lot of customers to take part in the automation, I'm only thinking this can go to the next step and allow for a smoother experience for the Ansible user. And a faster one also, invoking an Ansible module through a loop (like you'd do for hundreds of junctions) is killing it. Some optimizations inside the framework can reduce the deployment time of a reverse-proxy from hours to minutes. And I'm sure you could go faster.

Regards,

Cédric S.
